apiVersion: v1
kind: LimitRange
metadata:
  name: default-limits
spec:
  limits:
  - max:
      cpu: "2"
      memory: 1Gi
    type: Pod
  - default:
      cpu: 1500m
      memory: 500Mi
    defaultRequest:
      cpu: 500m
      memory: 50Mi
    type: Container