apiVersion: v1
kind: Pod
metadata:
  name: cpu-demo2
spec:
  containers:
  - name: cpu-demo-ctr
    image: vish/stress
    resources:
      limits:
        cpu: ".5"
      requests:
        cpu: "0.25"
    args:
    - -cpus
    - "1"
