apiVersion: v1
kind: Service
metadata:
  name: httpd-deployment-headless-with-selector
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: httpd
  clusterIP: None

