apiVersion: v1
kind: Pod
metadata:
  name: cpu-demo
spec:
  containers:
  - name: cpu-demo-ctr
    image: vish/stress
    resources:
      limits:
        cpu: "2.5"
      requests:
        cpu: "1.75"
    args:
    - -cpus
    - "1"
