apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: frontend-volume
  labels:
    app: guestbook-volume
    tier: frontend-volume
    web: apache-volume
spec:
  # modify replicas according to your case
  replicas: 2
  selector:
    matchLabels:
      tier: frontend-volume
  template:
    metadata:
      labels:
        tier: frontend-volume
    spec:
      containers:
        - name: alpine-apache
          image: devops459/alpine-apache:latest
          volumeMounts:
          - name: config-volume
            mountPath: /web/html/
      volumes:
        - name: config-volume
          configMap:
            name: custom-config
